package org.metadatacenter.cedar.resource.resources;

import com.codahale.metrics.annotation.Timed;
import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiImplicitParam;
import io.swagger.annotations.ApiImplicitParams;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import org.metadatacenter.cedar.resource.search.ValueSetsImportStatusManager;
import org.metadatacenter.config.CedarConfig;
import org.metadatacenter.exception.CedarException;
import org.metadatacenter.exception.CedarProcessingException;
import org.metadatacenter.rest.assertion.noun.CedarParameter;
import org.metadatacenter.rest.assertion.noun.CedarRequestBody;
import org.metadatacenter.rest.context.CedarRequestContext;
import org.metadatacenter.rest.context.CedarRequestContextFactory;
import org.metadatacenter.server.search.util.*;
import org.metadatacenter.server.security.model.auth.CedarPermission;
import org.metadatacenter.server.service.UserService;
import org.metadatacenter.util.http.CedarResponse;
import org.metadatacenter.util.json.JsonMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import static org.metadatacenter.rest.assertion.GenericAssertions.LoggedIn;

@Path("/command")
@Produces(MediaType.APPLICATION_JSON)
@Api(value = "/command", tags = "Command", authorizations = {@Authorization("api_key")})
public class CommandSearchResource extends AbstractResourceServerResource {

  private static final Logger log = LoggerFactory.getLogger(CommandSearchResource.class);
  private static UserService userService;

  public CommandSearchResource(CedarConfig cedarConfig) {
    super(cedarConfig);
  }

  public static void injectUserService(UserService us) {
    userService = us;
  }

  @POST
  @Timed
  @Path("/load-valuesets-ontology")
  @ApiOperation(value = "Load the OWL value sets ontology generated by the caDSR CDE injestor.",
      notes = "Load the OWL value sets ontology generated by the NCI caDSR CDE injestor. Each time the ingestor "
          + "runs (typically nightly) and new value sets ontology is created, which descibed the value sets used "
          + "by caDSR CDEs.")
  @ApiResponses({
      @ApiResponse(code = 200, message = "Successful operation"),
      @ApiResponse(code = 400, message = "Bad request"),
      @ApiResponse(code = 401, message = "Unauthorized"),
      @ApiResponse(code = 403, message = "Forbidden"),
      @ApiResponse(code = 404, message = "Not found"),
      @ApiResponse(code = 500, message = "Internal server error")
  })
  public Response loadValueSetsOntology() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);
    //c.must(c.user()).have(CedarPermission.SEARCH_INDEX_REINDEX);

    if (ValueSetsImportStatusManager.getInstance().getImportStatus() == ValueSetsImportStatusManager.ImportStatus.IN_PROGRESS) {
      return CedarResponse.badRequest().errorMessage("Value set loading already in progress").build();
    } else {
      ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.IN_PROGRESS);

      ExecutorService executor = Executors.newSingleThreadExecutor();
      executor.submit(() -> {
        LoadValueSetsOntologyTask task = new LoadValueSetsOntologyTask(cedarConfig);
        try {
          CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);

          task.loadValueSetsOntology(cedarAdminRequestContext);

          ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.COMPLETE);
        } catch (CedarProcessingException e) {
          ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.ERROR);
          log.error("Error in load value sets ontology executor", e);
        }
      });
      return Response.ok().build();
    }
  }

  @GET
  @Timed
  @Path("/load-valuesets-ontology-status")
  @ApiOperation(value = "Get the status of the value sets ontology loading",
      notes = "Get the current status of the value sets ontology loading process.")
  @ApiResponses({
      @ApiResponse(code = 200, message = "Successful operation"),
      @ApiResponse(code = 400, message = "Bad request"),
      @ApiResponse(code = 401, message = "Unauthorized"),
      @ApiResponse(code = 403, message = "Forbidden"),
      @ApiResponse(code = 404, message = "Not found"),
      @ApiResponse(code = 500, message = "Internal server error")
  })
  public Response loadValueSetsOntologyStatus() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);

    JsonNode output = JsonMapper.MAPPER.valueToTree(ValueSetsImportStatusManager.getInstance());
    return Response.ok().entity(output).build();
  }

  @POST
  @Timed
  @Path("/regenerate-search-index")
  @ApiOperation(value = "Regenerate search index.",
      notes = "Regenerate search index. This is an administrative command, you need special permission to run it. "
          + "If there is no need for reindexing, the task will not run. It can be forced using the force "
          + "parameter. A background task will be started. The status of the task can be monitored in the "
          + "resource server log files. While the reindexing runs, the old index is still used for searching. "
          + "Once the new index is ready, the old one will be removed, and the new one will be used for searching. "
          + "The reindexing computes permissions, it can run for a long time.",
      tags = {"Command", "Administration"})
  @ApiImplicitParams({
      @ApiImplicitParam(name = "forceRequest", value = "Force or not", required = true,
          dataType = "org.metadatacenter.cedar.resource.resources.swaggermodel.ForceRequest", paramType = "body")
  })
  @ApiResponses({
      @ApiResponse(code = 200, message = "Successful operation"),
      @ApiResponse(code = 400, message = "Bad request"),
      @ApiResponse(code = 401, message = "Unauthorized"),
      @ApiResponse(code = 403, message = "Forbidden"),
      @ApiResponse(code = 404, message = "Not found"),
      @ApiResponse(code = 500, message = "Internal server error")
  })
  public Response regenerateSearchIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);
    c.must(c.user()).have(CedarPermission.SEARCH_INDEX_REINDEX);

    CedarRequestBody requestBody = c.request().getRequestBody();
    CedarParameter forceParam = requestBody.get("force");
    final boolean force = forceParam.booleanValue();

    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(() -> {
      // 1. LOAD VALUE SETS ONTOLOGY. This step is only required in CEDAR installations that need to load CDEs into the
      // index (e.g., CEDAR Production). In those cases, this task ensures that the CDE values are available to be
      // indexed before the index regeneration task begins. In the case of installations that don't manage CDEs, this
      // task won't be able to load the CADSR-VS.owl file and will throw a warning.
      LoadValueSetsOntologyTask loadOntologyTask = new LoadValueSetsOntologyTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        loadOntologyTask.loadValueSetsOntology(cedarAdminRequestContext);
        ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.COMPLETE);
      } catch (CedarProcessingException e) {
        ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.ERROR);
        log.warn("Failed to load value sets ontology: " + e.getMessage());
      }

      // 2. REGENERATE SEARCH INDEX
      RegenerateSearchIndexTask regenerateIndexTask = new RegenerateSearchIndexTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        regenerateIndexTask.regenerateSearchIndex(force, cedarAdminRequestContext);
      } catch (CedarProcessingException e) {
        log.error("Error in index regeneration executor", e);
      }
    });

    return Response.ok().build();
  }

  @POST
  @Timed
  @Path("/generate-empty-search-index")
  @ApiOperation(value = "Empty search index.",
      notes = "Empty search index. This is an administrative command, you need special permission to run it. The "
          + "old index will be deleted and replaced by a new empty one. The search will work, but will not return "
          + "results, since the index will be empty.",
      tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(code = 200, message = "Successful operation"),
      @ApiResponse(code = 400, message = "Bad request"),
      @ApiResponse(code = 401, message = "Unauthorized"),
      @ApiResponse(code = 403, message = "Forbidden"),
      @ApiResponse(code = 404, message = "Not found"),
      @ApiResponse(code = 500, message = "Internal server error")
  })
  public Response generateEmptySearchIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);
    c.must(c.user()).have(CedarPermission.SEARCH_INDEX_REINDEX);

    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(() -> {
      GenerateEmptySearchIndexTask task = new GenerateEmptySearchIndexTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        task.generateEmptySearchIndex(cedarAdminRequestContext);
      } catch (CedarProcessingException e) {
        //TODO: handle this, log it separately
        log.error("Error in index regeneration executor", e);
      }
    });

    return Response.ok().build();
  }

  @POST
  @Timed
  @Path("/regenerate-rules-index")
  @ApiOperation(value = "Regenerate rules index.",
      notes = "Regenerate rules index. This is an administrative command, you need special permission to run it. "
          + "If there is no need for reindexing, the task will not run. It can be forced using the force "
          + "parameter. A background task will be started. The status of the task can be monitored in the "
          + "resource server log files. While the reindexing runs, the old index is still used for searching. "
          + "Once the new index is ready, the old one will be removed, and the new one will be used for searching. "
          + "The reindexing computes permissions, it can run for a long time.",
      tags = {"Command", "Administration"})
  @ApiImplicitParams({
      @ApiImplicitParam(name = "forceRequest", value = "Force or not", required = true,
          dataType = "org.metadatacenter.cedar.resource.resources.swaggermodel.ForceRequest", paramType = "body")
  })
  @ApiResponses({
      @ApiResponse(code = 200, message = "Successful operation"),
      @ApiResponse(code = 400, message = "Bad request"),
      @ApiResponse(code = 401, message = "Unauthorized"),
      @ApiResponse(code = 403, message = "Forbidden"),
      @ApiResponse(code = 404, message = "Not found"),
      @ApiResponse(code = 500, message = "Internal server error")
  })
  public Response regenerateRulesIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);
    c.must(c.user()).have(CedarPermission.RULES_INDEX_REINDEX);

    CedarRequestBody requestBody = c.request().getRequestBody();
    CedarParameter forceParam = requestBody.get("force");
    final boolean force = forceParam.booleanValue();
    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(() -> {
      RegenerateRulesIndexTask task = new RegenerateRulesIndexTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        task.regenerateRulesIndex(force, cedarAdminRequestContext);
      } catch (CedarProcessingException e) {
        //TODO: handle this, log it separately
        log.error("Error in index regeneration executor", e);
      }
    });

    return Response.ok().build();
  }

  @POST
  @Timed
  @Path("/generate-empty-rules-index")
  @ApiOperation(value = "Empty rules index.",
      notes = "Regenerate rules index. This is an administrative command, you need special permission to run it. "
          + "The old index will be deleted and replaced by a new empty one. The recommendations will work, but "
          + "will not return results, since the index will be empty.",
      tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(code = 200, message = "Successful operation"),
      @ApiResponse(code = 400, message = "Bad request"),
      @ApiResponse(code = 401, message = "Unauthorized"),
      @ApiResponse(code = 403, message = "Forbidden"),
      @ApiResponse(code = 404, message = "Not found"),
      @ApiResponse(code = 500, message = "Internal server error")
  })
  public Response generateEmptyRulesIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);
    c.must(c.user()).have(CedarPermission.SEARCH_INDEX_REINDEX);

    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(() -> {
      GenerateEmptyRulesIndexTask task = new GenerateEmptyRulesIndexTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        task.generateEmptyRulesIndex(cedarAdminRequestContext);
      } catch (CedarProcessingException e) {
        //TODO: handle this, log it separately
        log.error("Error in index regeneration executor", e);
      }
    });

    return Response.ok().build();
  }

}
