package org.metadatacenter.cedar.resource.resources;

import com.codahale.metrics.annotation.Timed;
import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.metadatacenter.cedar.resource.search.ValueSetsImportStatusManager;
import org.metadatacenter.config.CedarConfig;
import org.metadatacenter.exception.CedarException;
import org.metadatacenter.exception.CedarProcessingException;
import org.metadatacenter.rest.assertion.noun.CedarParameter;
import org.metadatacenter.rest.assertion.noun.CedarRequestBody;
import org.metadatacenter.rest.context.CedarRequestContext;
import org.metadatacenter.rest.context.CedarRequestContextFactory;
import org.metadatacenter.cedar.resource.security.AdminCommand;
import org.metadatacenter.server.search.util.*;
import org.metadatacenter.server.service.UserService;
import org.metadatacenter.util.http.CedarResponse;
import org.metadatacenter.util.json.JsonMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import static org.metadatacenter.rest.assertion.GenericAssertions.LoggedIn;

@Path("/command")
@Produces(MediaType.APPLICATION_JSON)
@Tag(name = "Command")
@SecurityRequirement(name = "api_key")
public class CommandSearchResource extends AbstractResourceServerResource {

  private static final Logger log = LoggerFactory.getLogger(CommandSearchResource.class);
  private static UserService userService;

  public CommandSearchResource(CedarConfig cedarConfig) {
    super(cedarConfig);
  }

  public static void injectUserService(UserService us) {
    userService = us;
  }

  @POST
  @Timed
  @Path("/load-valuesets-ontology")
  @Operation(summary = "Load the OWL value sets ontology generated by the caDSR CDE injestor.", description = "Load the OWL value sets ontology generated by the NCI caDSR CDE injestor. Each time the ingestor "
          + "runs (typically nightly) and new value sets ontology is created, which descibed the value sets used "
          + "by caDSR CDEs.")
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "Successful operation"),
      @ApiResponse(responseCode = "400", description = "Bad request"),
      @ApiResponse(responseCode = "401", description = "Unauthorized"),
      @ApiResponse(responseCode = "403", description = "Forbidden"),
      @ApiResponse(responseCode = "404", description = "Not found"),
      @ApiResponse(responseCode = "500", description = "Internal server error")
  })
  public Response loadValueSetsOntology() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.LOAD_VALUESETS_ONTOLOGY.enforce(c);

    if (ValueSetsImportStatusManager.getInstance().getImportStatus() == ValueSetsImportStatusManager.ImportStatus.IN_PROGRESS) {
      return CedarResponse.badRequest().errorMessage("Value set loading already in progress").build();
    } else {
      ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.IN_PROGRESS);

      ExecutorService executor = Executors.newSingleThreadExecutor();
      executor.submit(() -> {
        LoadValueSetsOntologyTask task = new LoadValueSetsOntologyTask(cedarConfig);
        try {
          CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);

          task.loadValueSetsOntology(cedarAdminRequestContext);

          ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.COMPLETE);
        } catch (CedarProcessingException e) {
          ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.ERROR);
          log.error("Error in load value sets ontology executor", e);
        }
      });
      executor.shutdown();
      return Response.ok().build();
    }
  }

  @GET
  @Timed
  @Path("/load-valuesets-ontology-status")
  @Operation(summary = "Get the status of the value sets ontology loading", description = "Get the current status of the value sets ontology loading process.")
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "Successful operation"),
      @ApiResponse(responseCode = "400", description = "Bad request"),
      @ApiResponse(responseCode = "401", description = "Unauthorized"),
      @ApiResponse(responseCode = "403", description = "Forbidden"),
      @ApiResponse(responseCode = "404", description = "Not found"),
      @ApiResponse(responseCode = "500", description = "Internal server error")
  })
  public Response loadValueSetsOntologyStatus() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);

    JsonNode output = JsonMapper.MAPPER.valueToTree(ValueSetsImportStatusManager.getInstance());
    return Response.ok().entity(output).build();
  }

  @POST
  @Timed
  @Path("/regenerate-search-index")
  @Operation(summary = "Regenerate search index.", description = "Regenerate search index. This is an administrative command, you need special permission to run it. "
          + "If there is no need for reindexing, the task will not run. It can be forced using the force "
          + "parameter. A background task will be started. The status of the task can be monitored in the "
          + "resource server log files. While the reindexing runs, the old index is still used for searching. "
          + "Once the new index is ready, the old one will be removed, and the new one will be used for searching. "
          + "The reindexing computes permissions, it can run for a long time.", tags = {"Command", "Administration"})
  @RequestBody(description = "Force or not", required = true, content = @Content(schema = @Schema(implementation = org.metadatacenter.cedar.resource.resources.swaggermodel.ForceRequest.class)))
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "Successful operation"),
      @ApiResponse(responseCode = "400", description = "Bad request"),
      @ApiResponse(responseCode = "401", description = "Unauthorized"),
      @ApiResponse(responseCode = "403", description = "Forbidden"),
      @ApiResponse(responseCode = "404", description = "Not found"),
      @ApiResponse(responseCode = "500", description = "Internal server error")
  })
  public Response regenerateSearchIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.REGENERATE_SEARCH_INDEX.enforce(c);

    CedarRequestBody requestBody = c.request().getRequestBody();
    CedarParameter forceParam = requestBody.get("force");
    final boolean force = forceParam.booleanValue();

    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(() -> {
      // 1. LOAD VALUE SETS ONTOLOGY. This step is only required in CEDAR installations that need to load CDEs into the
      // index (e.g., CEDAR Production). In those cases, this task ensures that the CDE values are available to be
      // indexed before the index regeneration task begins. In the case of installations that don't manage CDEs, this
      // task won't be able to load the CADSR-VS.owl file and will throw a warning.
      LoadValueSetsOntologyTask loadOntologyTask = new LoadValueSetsOntologyTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        loadOntologyTask.loadValueSetsOntology(cedarAdminRequestContext);
        ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.COMPLETE);
      } catch (CedarProcessingException e) {
        ValueSetsImportStatusManager.getInstance().setImportStatus(ValueSetsImportStatusManager.ImportStatus.ERROR);
        log.warn("Failed to load value sets ontology: " + e.getMessage());
      }

      // 2. REGENERATE SEARCH INDEX
      RegenerateSearchIndexTask regenerateIndexTask = new RegenerateSearchIndexTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        regenerateIndexTask.regenerateSearchIndex(force, cedarAdminRequestContext);
      } catch (CedarProcessingException e) {
        log.error("Error in index regeneration executor", e);
      }
    });
    executor.shutdown();

    return Response.ok().build();
  }

  @POST
  @Timed
  @Path("/generate-empty-search-index")
  @Operation(summary = "Empty search index.", description = "Empty search index. This is an administrative command, you need special permission to run it. The "
          + "old index will be deleted and replaced by a new empty one. The search will work, but will not return "
          + "results, since the index will be empty.", tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "Successful operation"),
      @ApiResponse(responseCode = "400", description = "Bad request"),
      @ApiResponse(responseCode = "401", description = "Unauthorized"),
      @ApiResponse(responseCode = "403", description = "Forbidden"),
      @ApiResponse(responseCode = "404", description = "Not found"),
      @ApiResponse(responseCode = "500", description = "Internal server error")
  })
  public Response generateEmptySearchIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.GENERATE_EMPTY_SEARCH_INDEX.enforce(c);

    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(() -> {
      GenerateEmptySearchIndexTask task = new GenerateEmptySearchIndexTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        task.generateEmptySearchIndex(cedarAdminRequestContext);
      } catch (CedarProcessingException e) {
        //TODO: handle this, log it separately
        log.error("Error in index regeneration executor", e);
      }
    });
    executor.shutdown();

    return Response.ok().build();
  }

  @POST
  @Timed
  @Path("/regenerate-rules-index")
  @Operation(summary = "Regenerate rules index. Deprecated: this command empties the rules index.", description =
      "Deprecated, and does not do what its name says. The rules index holds association rules mined by the value "
          + "recommender from template instances; the resource server cannot produce those documents. This command "
          + "creates an empty index, points the alias at it and deletes the old index, so it discards every rule in "
          + "the system and recommendations stop returning results. The force parameter is read but has no effect. "
          + "Use /command/generate-empty-rules-index if emptying the index is what you want. To repopulate the "
          + "index, call the value recommender's /command/generate-rules/{template_id} for each template.",
      deprecated = true, tags = {"Command", "Administration"})
  @RequestBody(description = "Force or not", required = true, content = @Content(schema = @Schema(implementation = org.metadatacenter.cedar.resource.resources.swaggermodel.ForceRequest.class)))
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "Successful operation"),
      @ApiResponse(responseCode = "400", description = "Bad request"),
      @ApiResponse(responseCode = "401", description = "Unauthorized"),
      @ApiResponse(responseCode = "403", description = "Forbidden"),
      @ApiResponse(responseCode = "404", description = "Not found"),
      @ApiResponse(responseCode = "500", description = "Internal server error")
  })
  @Deprecated
  public Response regenerateRulesIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.REGENERATE_RULES_INDEX.enforce(c);

    log.warn("/command/regenerate-rules-index is deprecated: it empties the rules index instead of rebuilding it. "
        + "Rules must be regenerated through the value recommender.");

    CedarRequestBody requestBody = c.request().getRequestBody();
    CedarParameter forceParam = requestBody.get("force");
    final boolean force = forceParam.booleanValue();
    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(() -> {
      RegenerateRulesIndexTask task = new RegenerateRulesIndexTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        task.regenerateRulesIndex(force, cedarAdminRequestContext);
      } catch (CedarProcessingException e) {
        //TODO: handle this, log it separately
        log.error("Error in index regeneration executor", e);
      }
    });
    executor.shutdown();

    return Response.ok().build();
  }

  @POST
  @Timed
  @Path("/generate-empty-rules-index")
  @Operation(summary = "Empty rules index.", description = "Regenerate rules index. This is an administrative command, you need special permission to run it. "
          + "The old index will be deleted and replaced by a new empty one. The recommendations will work, but "
          + "will not return results, since the index will be empty.", tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "Successful operation"),
      @ApiResponse(responseCode = "400", description = "Bad request"),
      @ApiResponse(responseCode = "401", description = "Unauthorized"),
      @ApiResponse(responseCode = "403", description = "Forbidden"),
      @ApiResponse(responseCode = "404", description = "Not found"),
      @ApiResponse(responseCode = "500", description = "Internal server error")
  })
  public Response generateEmptyRulesIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.GENERATE_EMPTY_RULES_INDEX.enforce(c);

    ExecutorService executor = Executors.newSingleThreadExecutor();
    executor.submit(() -> {
      GenerateEmptyRulesIndexTask task = new GenerateEmptyRulesIndexTask(cedarConfig);
      try {
        CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
        task.generateEmptyRulesIndex(cedarAdminRequestContext);
      } catch (CedarProcessingException e) {
        //TODO: handle this, log it separately
        log.error("Error in index regeneration executor", e);
      }
    });
    executor.shutdown();

    return Response.ok().build();
  }

}
