package org.metadatacenter.cedar.resource.resources;

import com.codahale.metrics.annotation.Timed;
import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.metadatacenter.util.http.CedarError;
import org.metadatacenter.cedar.resource.search.IndexJobGuard;
import org.metadatacenter.cedar.resource.search.JobClaim;
import org.metadatacenter.cedar.resource.search.ValueSetsImportStatusManager;
import org.metadatacenter.config.CedarConfig;
import org.metadatacenter.exception.CedarException;
import org.metadatacenter.rest.assertion.noun.CedarParameter;
import org.metadatacenter.rest.assertion.noun.CedarRequestBody;
import org.metadatacenter.rest.context.CedarRequestContext;
import org.metadatacenter.rest.context.CedarRequestContextFactory;
import org.metadatacenter.cedar.resource.security.AdminCommand;
import org.metadatacenter.server.search.util.*;
import org.metadatacenter.server.service.UserService;
import org.metadatacenter.util.http.CedarResponse;
import org.metadatacenter.util.json.JsonMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.HttpHeaders;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import java.net.URI;
import java.util.Optional;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.function.Supplier;

import static org.metadatacenter.rest.assertion.GenericAssertions.LoggedIn;

@Path("/command")
@Produces(MediaType.APPLICATION_JSON)
@Tag(name = "Command")
@SecurityRequirement(name = "api_key")
public class CommandSearchResource extends AbstractResourceServerResource {

  private static final Logger log = LoggerFactory.getLogger(CommandSearchResource.class);
  private static UserService userService;

  private static final String RESET_DESCRIPTION =
      "Only one rebuild or import runs at a time, and a job that never returns would otherwise hold its claim "
          + "until the server restarted, refusing every later command with a conflict naming a job that is not "
          + "running. A claim is believed for six hours; past that the status reports it as overdue and this "
          + "command takes it back, so the next command can run. It does not stop the abandoned job — nothing "
          + "can — so run it only once the log shows that job has stopped making progress. A claim within its "
          + "deadline is left alone, and answers with a conflict.";

  private static final String QUEUED_DESCRIPTION =
      " The work is asynchronous, so this answers as soon as the job is queued rather than once it has been "
          + "done: 202, the job's identifier, and a Location header naming where to poll it. A 200 would say "
          + "the work had finished, which is the one thing this response cannot mean.";

  public CommandSearchResource(CedarConfig cedarConfig) {
    super(cedarConfig);
  }

  public static void injectUserService(UserService us) {
    userService = us;
  }

  @POST
  @Timed
  @Path("/load-valuesets-ontology")
  @Operation(summary = "Load the OWL value sets ontology generated by the caDSR CDE injestor.", description = "Load the OWL value sets ontology generated by the NCI caDSR CDE injestor. Each time the ingestor "
          + "runs (typically nightly) and new value sets ontology is created, which descibed the value sets used "
          + "by caDSR CDEs." + QUEUED_DESCRIPTION)
  @ApiResponses({
      @ApiResponse(responseCode = "202", description = "The import was queued",
          headers = @Header(name = "Location", description = "Where to poll this import.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "400", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Bad request"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Not found"),
      @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "An import is already running",
          headers = @Header(name = "Location", description = "Where to poll the running import.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response loadValueSetsOntology() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.LOAD_VALUESETS_ONTOLOGY.enforce(c);

    Optional<JobClaim> claim = ValueSetsImportStatusManager.getInstance().tryStart();
    if (claim.isEmpty()) {
      return importAlreadyRunning();
    }

    submitValueSetsImportJob(claim.get(), () -> {
      LoadValueSetsOntologyTask task = new LoadValueSetsOntologyTask(cedarConfig);
      CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
      task.loadValueSetsOntology(cedarAdminRequestContext);
    });

    return importQueued(claim.get());
  }

  @GET
  @Timed
  @Path("/load-valuesets-ontology-status")
  @Operation(summary = "Get the status of the value sets ontology loading",
      description = "Get the current status of the latest value sets ontology import, whichever import that is. "
          + "To follow one import in particular, poll it by the identifier its command returned.")
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "Successful operation"),
      @ApiResponse(responseCode = "400", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Bad request"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Not found"),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response loadValueSetsOntologyStatus() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);

    JsonNode output = JsonMapper.MAPPER.valueToTree(ValueSetsImportStatusManager.getInstance());
    return Response.ok().entity(output).build();
  }

  @GET
  @Timed
  @Path("/load-valuesets-ontology-status/{jobId}")
  @Operation(summary = "Get the status of one value sets ontology import",
      description = "Report what became of the import named by the identifier its command returned, rather than "
          + "of whichever import ran last. Imports are held in memory, so an identifier from before the last "
          + "restart, or one that twenty later imports have pushed out, is no longer known.")
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "The import and its current state"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "No import answers to this identifier"),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response loadValueSetsOntologyStatusById(
      @Parameter(description = "Import identifier, as returned when the import was queued.", required = true)
      @PathParam("jobId") String jobId) throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);

    return ValueSetsImportStatusManager.getInstance().find(jobId)
        .map(job -> Response.ok().entity(JsonMapper.MAPPER.valueToTree(job)).build())
        .orElseGet(() -> noSuchJob("value sets ontology import", jobId));
  }

  /** Where a caller polls one index job, whether it started the job or was refused by it. */
  private static URI indexJobUri(String jobId) {
    return URI.create("/command/index-job-status/" + jobId);
  }

  /** The same for the value sets ontology import, which has a status of its own. */
  private static URI importJobUri(String jobId) {
    return URI.create("/command/load-valuesets-ontology-status/" + jobId);
  }

  /**
   * A rebuild that has been queued rather than performed. The identifier is the claim's own, so the
   * Location names the job this request started even if it has already finished by the time the
   * response is built; the body is that job as the status route renders it.
   */
  private static Response queued(IndexJobGuard.Index index, JobClaim claim) {
    IndexJobGuard.Status job = IndexJobGuard.find(claim.id()).orElseGet(() -> IndexJobGuard.status(index));
    return Response.accepted(JsonMapper.MAPPER.valueToTree(job)).location(indexJobUri(claim.id())).build();
  }

  /** An import that has been queued rather than performed, reported the way a queued rebuild is. */
  private static Response importQueued(JobClaim claim) {
    ValueSetsImportStatusManager imports = ValueSetsImportStatusManager.getInstance();
    ValueSetsImportStatusManager.ImportJob job = imports.find(claim.id()).orElseGet(imports::snapshot);
    return Response.accepted(JsonMapper.MAPPER.valueToTree(job)).location(importJobUri(claim.id())).build();
  }

  /**
   * A rebuild of this index is already running, so this one does not start. 409 rather than 400: the
   * request is well formed and will be accepted once the running job finishes.
   *
   * <p>A claim past its deadline says so and names the way out, because that is the case in which the
   * caller is otherwise told to wait for a job that may have stopped running hours ago.
   *
   * <p>The refusal names the running job and where to poll it, so a caller that wanted a rebuild has
   * something to wait on rather than only a reason it was refused.
   */
  private static Response alreadyRunning(IndexJobGuard.Index index) {
    IndexJobGuard.Status status = IndexJobGuard.status(index);
    return CedarResponse.conflict()
        .header(HttpHeaders.LOCATION, indexJobUri(status.jobId()))
        .errorMessage("A " + status.command() + " job started at " + status.startedAt()
            + " is still running over the " + index.name().toLowerCase() + " index"
            + (status.overdue()
               ? ", and it passed its deadline at " + status.deadlineAt()
                 + ". Reset it with POST " + resetPath(index) + " if it has stopped making progress"
               : ""))
        .parameter("jobId", status.jobId())
        .parameter("index", index.name())
        .parameter("command", status.command())
        .parameter("startedAt", status.startedAt())
        .parameter("deadlineAt", status.deadlineAt())
        .parameter("overdue", status.overdue())
        .build();
  }

  /** An import is already running, reported the way a busy index is. */
  private static Response importAlreadyRunning() {
    ValueSetsImportStatusManager imports = ValueSetsImportStatusManager.getInstance();
    return CedarResponse.conflict()
        .header(HttpHeaders.LOCATION, importJobUri(imports.getJobId()))
        .errorMessage("A value sets ontology import started at " + imports.getStartedAt() + " is still running"
            + (imports.isOverdue()
               ? ", and it passed its deadline at " + imports.getDeadlineAt()
                 + ". Reset it with POST /command/reset-valuesets-import if it has stopped making progress"
               : ""))
        .parameter("jobId", imports.getJobId())
        .parameter("startedAt", imports.getStartedAt())
        .parameter("deadlineAt", imports.getDeadlineAt())
        .parameter("overdue", imports.isOverdue())
        .build();
  }

  @GET
  @Timed
  @Path("/index-job-status")
  @Operation(summary = "Status of the index rebuild jobs", description = "What became of the most recent rebuild of "
          + "each index, and whether one is running now. A rebuild is queued rather than performed, so this is "
          + "where its outcome is reported. To follow one rebuild in particular, poll it by the identifier its "
          + "command returned.", tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "Successful operation"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response indexJobStatus() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);

    return Response.ok().entity(JsonMapper.MAPPER.valueToTree(IndexJobGuard.statuses())).build();
  }

  @GET
  @Timed
  @Path("/index-job-status/{jobId}")
  @Operation(summary = "Status of one index rebuild job", description = "Report what became of the rebuild named "
          + "by the identifier its command returned. Reading an index instead answers a different question: it "
          + "says what the last job over that index did, which is the same job only until another command runs. "
          + "Jobs are held in memory, so an identifier from before the last restart, or one that twenty later "
          + "jobs have pushed out, is no longer known.", tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "The job and its current state"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "No job answers to this identifier"),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response indexJobStatusById(
      @Parameter(description = "Job identifier, as returned when the rebuild was queued.", required = true)
      @PathParam("jobId") String jobId) throws CedarException {
    CedarRequestContext c = buildRequestContext();
    c.must(c.user()).be(LoggedIn);

    return IndexJobGuard.find(jobId)
        .map(status -> Response.ok().entity(JsonMapper.MAPPER.valueToTree(status)).build())
        .orElseGet(() -> noSuchJob("index rebuild", jobId));
  }

  /**
   * Nothing answers to this identifier. Said as a 404 rather than as an empty status, because a
   * caller polling a job it started needs to tell "not finished yet" from "no longer known": the
   * first is worth waiting on and the second never resolves.
   */
  private static Response noSuchJob(String kind, String jobId) {
    return CedarResponse.notFound()
        .errorMessage("No " + kind + " answers to " + jobId
            + ". Jobs are held in memory, so an identifier from before the last restart, or one that later "
            + "jobs have pushed out, is no longer known")
        .parameter("jobId", jobId)
        .build();
  }

  /** Each index is claimed on its own, so each is taken back on its own and under its own permission. */
  private static String resetPath(IndexJobGuard.Index index) {
    return index == IndexJobGuard.Index.SEARCH ? "/command/reset-search-index-job" : "/command/reset-rules-index-job";
  }

  @POST
  @Timed
  @Path("/reset-search-index-job")
  @Operation(summary = "Take back a search index rebuild that passed its deadline.", description = RESET_DESCRIPTION,
      tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "The claim was reset, and the index is free"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Nothing is running, or the running job is within its deadline"),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response resetSearchIndexJob() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.RESET_SEARCH_INDEX_JOB.enforce(c);

    return resetIndexJob(IndexJobGuard.Index.SEARCH);
  }

  @POST
  @Timed
  @Path("/reset-rules-index-job")
  @Operation(summary = "Take back a rules index rebuild that passed its deadline.", description = RESET_DESCRIPTION,
      tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "The claim was reset, and the index is free"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Nothing is running, or the running job is within its deadline"),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response resetRulesIndexJob() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.RESET_RULES_INDEX_JOB.enforce(c);

    return resetIndexJob(IndexJobGuard.Index.RULES);
  }

  private Response resetIndexJob(IndexJobGuard.Index index) {
    if (!IndexJobGuard.reset(index)) {
      IndexJobGuard.Status status = IndexJobGuard.status(index);
      return CedarResponse.conflict()
          .errorMessage("Nothing to reset on the " + index.name().toLowerCase() + " index: it is "
              + status.state().name().toLowerCase()
              + (status.state() == IndexJobGuard.State.RUNNING
                 ? " and within its deadline, which expires at " + status.deadlineAt() : ""))
          .parameter("index", index.name())
          .parameter("state", status.state().name())
          .parameter("deadlineAt", status.deadlineAt())
          .build();
    }
    return Response.ok().entity(JsonMapper.MAPPER.valueToTree(IndexJobGuard.status(index))).build();
  }

  @POST
  @Timed
  @Path("/reset-valuesets-import")
  @Operation(summary = "Take back a value sets ontology import that passed its deadline.",
      description = RESET_DESCRIPTION, tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "200", description = "The claim was reset, and the import is free"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Nothing is running, or the running import is within its deadline"),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response resetValueSetsImport() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.RESET_VALUESETS_IMPORT.enforce(c);

    ValueSetsImportStatusManager imports = ValueSetsImportStatusManager.getInstance();
    if (!imports.reset()) {
      return CedarResponse.conflict()
          .errorMessage("Nothing to reset: the value sets ontology import is "
              + imports.getImportStatus().name().toLowerCase()
              + (imports.getImportStatus() == ValueSetsImportStatusManager.ImportStatus.IN_PROGRESS
                 ? " and within its deadline, which expires at " + imports.getDeadlineAt() : ""))
          .parameter("importStatus", imports.getImportStatus().name())
          .parameter("deadlineAt", imports.getDeadlineAt())
          .build();
    }
    return Response.ok().entity(JsonMapper.MAPPER.valueToTree(imports)).build();
  }

  @POST
  @Timed
  @Path("/regenerate-search-index")
  @Operation(summary = "Regenerate search index.", description = "Regenerate search index. This is an administrative command, you need special permission to run it. "
          + "If there is no need for reindexing, the task will not run. It can be forced using the force "
          + "parameter. While the reindexing runs, the old index is still used for searching. "
          + "Once the new index is ready, the old one will be removed, and the new one will be used for searching. "
          + "The reindexing computes permissions, it can run for a long time." + QUEUED_DESCRIPTION,
      tags = {"Command", "Administration"})
  @RequestBody(description = "Force or not", required = true, content = @Content(schema = @Schema(implementation = org.metadatacenter.cedar.resource.resources.swaggermodel.ForceRequest.class)))
  @ApiResponses({
      @ApiResponse(responseCode = "202", description = "The rebuild was queued",
          headers = @Header(name = "Location", description = "Where to poll this job's status.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "400", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Bad request"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Not found"),
      @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "A rebuild of this index is already running",
          headers = @Header(name = "Location", description = "Where to poll the running job's status.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response regenerateSearchIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.REGENERATE_SEARCH_INDEX.enforce(c);

    CedarRequestBody requestBody = c.request().getRequestBody();
    CedarParameter forceParam = requestBody.get("force");
    final boolean force = forceParam.booleanValue();

    Optional<JobClaim> claim = IndexJobGuard.tryStart(IndexJobGuard.Index.SEARCH, "regenerate-search-index");
    if (claim.isEmpty()) {
      return alreadyRunning(IndexJobGuard.Index.SEARCH);
    }

    submitClaimedIndexJob(IndexJobGuard.Index.SEARCH, claim.get(), "search index regeneration", () -> {
      // 1. LOAD VALUE SETS ONTOLOGY. This step is only required in CEDAR installations that need to load CDEs into the
      // index (e.g., CEDAR Production). In those cases, this task ensures that the CDE values are available to be
      // indexed before the index regeneration task begins. In the case of installations that don't manage CDEs, this
      // task won't be able to load the CADSR-VS.owl file and will throw a warning.
      //
      // The import is claimed here as /command/load-valuesets-ontology claims it. This route used to run
      // the same task without claiming, so a regeneration could load the ontology alongside an import
      // already running, and report COMPLETE over the status of the import that was still going.
      ValueSetsImportStatusManager imports = ValueSetsImportStatusManager.getInstance();
      Optional<JobClaim> importClaim = imports.tryStart();
      if (importClaim.isEmpty()) {
        log.warn("A value sets ontology import is already running, so this regeneration does not load it again");
      } else {
        LoadValueSetsOntologyTask loadOntologyTask = new LoadValueSetsOntologyTask(cedarConfig);
        try {
          CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
          loadOntologyTask.loadValueSetsOntology(cedarAdminRequestContext);
          imports.finish(importClaim.get(), null);
        } catch (Exception e) {
          imports.finish(importClaim.get(), e);
          log.warn("Failed to load value sets ontology", e);
        }
      }

      // 2. REGENERATE SEARCH INDEX
      RegenerateSearchIndexTask regenerateIndexTask = new RegenerateSearchIndexTask(cedarConfig);
      CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
      regenerateIndexTask.regenerateSearchIndex(force, cedarAdminRequestContext);
    });

    return queued(IndexJobGuard.Index.SEARCH, claim.get());
  }

  @POST
  @Timed
  @Path("/generate-empty-search-index")
  @Operation(summary = "Empty search index.", description = "Empty search index. This is an administrative command, you need special permission to run it. The "
          + "old index will be deleted and replaced by a new empty one. The search will work, but will not return "
          + "results, since the index will be empty." + QUEUED_DESCRIPTION, tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "202", description = "The rebuild was queued",
          headers = @Header(name = "Location", description = "Where to poll this job's status.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "400", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Bad request"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Not found"),
      @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "A rebuild of this index is already running",
          headers = @Header(name = "Location", description = "Where to poll the running job's status.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response generateEmptySearchIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.GENERATE_EMPTY_SEARCH_INDEX.enforce(c);

    Optional<JobClaim> claim = IndexJobGuard.tryStart(IndexJobGuard.Index.SEARCH, "generate-empty-search-index");
    if (claim.isEmpty()) {
      return alreadyRunning(IndexJobGuard.Index.SEARCH);
    }

    submitClaimedIndexJob(IndexJobGuard.Index.SEARCH, claim.get(), "empty search index generation", () -> {
      GenerateEmptySearchIndexTask task = new GenerateEmptySearchIndexTask(cedarConfig);
      CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
      task.generateEmptySearchIndex(cedarAdminRequestContext);
    });

    return queued(IndexJobGuard.Index.SEARCH, claim.get());
  }

  @POST
  @Timed
  @Path("/regenerate-rules-index")
  @Operation(summary = "Regenerate rules index. Deprecated: this command empties the rules index.", description =
      "Deprecated, and does not do what its name says. The rules index holds association rules mined by the value "
          + "recommender from template instances; the resource server cannot produce those documents. This command "
          + "creates an empty index, points the alias at it and deletes the old index, so it discards every rule in "
          + "the system and recommendations stop returning results. The force parameter is read but has no effect. "
          + "Use /command/generate-empty-rules-index if emptying the index is what you want. To repopulate the "
          + "index, call the value recommender's /command/generate-rules/{template_id} for each template."
          + QUEUED_DESCRIPTION, deprecated = true, tags = {"Command", "Administration"})
  @RequestBody(description = "Force or not", required = true, content = @Content(schema = @Schema(implementation = org.metadatacenter.cedar.resource.resources.swaggermodel.ForceRequest.class)))
  @ApiResponses({
      @ApiResponse(responseCode = "202", description = "The rebuild was queued",
          headers = @Header(name = "Location", description = "Where to poll this job's status.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "400", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Bad request"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Not found"),
      @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "A rebuild of this index is already running",
          headers = @Header(name = "Location", description = "Where to poll the running job's status.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  @Deprecated
  public Response regenerateRulesIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.REGENERATE_RULES_INDEX.enforce(c);

    log.warn("/command/regenerate-rules-index is deprecated: it empties the rules index instead of rebuilding it. "
        + "Rules must be regenerated through the value recommender.");

    CedarRequestBody requestBody = c.request().getRequestBody();
    CedarParameter forceParam = requestBody.get("force");
    final boolean force = forceParam.booleanValue();
    Optional<JobClaim> claim = IndexJobGuard.tryStart(IndexJobGuard.Index.RULES, "regenerate-rules-index");
    if (claim.isEmpty()) {
      return alreadyRunning(IndexJobGuard.Index.RULES);
    }

    submitClaimedIndexJob(IndexJobGuard.Index.RULES, claim.get(), "rules index regeneration", () -> {
      RegenerateRulesIndexTask task = new RegenerateRulesIndexTask(cedarConfig);
      CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
      task.regenerateRulesIndex(force, cedarAdminRequestContext);
    });

    return queued(IndexJobGuard.Index.RULES, claim.get());
  }

  @POST
  @Timed
  @Path("/generate-empty-rules-index")
  @Operation(summary = "Empty rules index.", description = "Regenerate rules index. This is an administrative command, you need special permission to run it. "
          + "The old index will be deleted and replaced by a new empty one. The recommendations will work, but "
          + "will not return results, since the index will be empty." + QUEUED_DESCRIPTION,
      tags = {"Command", "Administration"})
  @ApiResponses({
      @ApiResponse(responseCode = "202", description = "The rebuild was queued",
          headers = @Header(name = "Location", description = "Where to poll this job's status.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "400", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Bad request"),
      @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Unauthorized"),
      @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Forbidden"),
      @ApiResponse(responseCode = "404", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Not found"),
      @ApiResponse(responseCode = "409", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "A rebuild of this index is already running",
          headers = @Header(name = "Location", description = "Where to poll the running job's status.",
              schema = @Schema(type = "string"))),
      @ApiResponse(responseCode = "500", content = @Content(schema = @Schema(implementation = CedarError.class)), description = "Internal server error")
  })
  public Response generateEmptyRulesIndex() throws CedarException {
    CedarRequestContext c = buildRequestContext();
    AdminCommand.GENERATE_EMPTY_RULES_INDEX.enforce(c);

    Optional<JobClaim> claim = IndexJobGuard.tryStart(IndexJobGuard.Index.RULES, "generate-empty-rules-index");
    if (claim.isEmpty()) {
      return alreadyRunning(IndexJobGuard.Index.RULES);
    }

    submitClaimedIndexJob(IndexJobGuard.Index.RULES, claim.get(), "empty rules index generation", () -> {
      GenerateEmptyRulesIndexTask task = new GenerateEmptyRulesIndexTask(cedarConfig);
      CedarRequestContext cedarAdminRequestContext = CedarRequestContextFactory.fromAdminUser(cedarConfig, userService);
      task.generateEmptyRulesIndex(cedarAdminRequestContext);
    });

    return queued(IndexJobGuard.Index.RULES, claim.get());
  }

  /**
   * Hands a claimed index job to a thread of its own, releasing the claim if it never gets there.
   *
   * <p>{@link IndexJobGuard#runClaimed} releases the index on every path the job itself can take,
   * but only once the job runs. Between the claim and the job's first instruction sits the executor:
   * creating a thread, and accepting the task. Either can fail, and the claim taken a moment earlier
   * would then be held on behalf of a job that never started, so every subsequent rebuild is refused
   * with a 409 naming a job that is not running until the claim passes its deadline hours later.
   *
   * <p>A failure to start is reported rather than swallowed. Answering 200 for a rebuild that was
   * never scheduled tells the caller the opposite of what happened.
   */
  private static void submitClaimedIndexJob(IndexJobGuard.Index index, JobClaim claim, String description,
                                            IndexJobGuard.Job job) {
    submitClaimedIndexJob(index, claim, description, job, Executors::newSingleThreadExecutor);
  }

  /** The executor is supplied so a test can hand over one that cannot create a thread or take a task. */
  static void submitClaimedIndexJob(IndexJobGuard.Index index, JobClaim claim, String description,
                                    IndexJobGuard.Job job, Supplier<ExecutorService> executors) {
    ExecutorService executor = null;
    try {
      executor = executors.get();
      executor.submit(() -> runClaimedIndexJob(index, claim, description, job));
    } catch (RuntimeException | Error e) {
      IndexJobGuard.finish(index, claim, e);
      log.error("Could not start {}; released the index claim", description, e);
      throw e;
    } finally {
      if (executor != null) {
        executor.shutdown();
      }
    }
  }

  private static void runClaimedIndexJob(IndexJobGuard.Index index, JobClaim claim, String description,
                                         IndexJobGuard.Job job) {
    try {
      IndexJobGuard.runClaimed(index, claim, job);
    } catch (Exception e) {
      log.error("Error in {} executor", description, e);
    }
  }

  /** The value sets import is handed to a thread the same way, and released on the same failure to start. */
  private static void submitValueSetsImportJob(JobClaim claim, IndexJobGuard.Job job) {
    submitValueSetsImportJob(claim, job, Executors::newSingleThreadExecutor);
  }

  static void submitValueSetsImportJob(JobClaim claim, IndexJobGuard.Job job,
                                       Supplier<ExecutorService> executors) {
    ExecutorService executor = null;
    try {
      executor = executors.get();
      executor.submit(() -> runValueSetsImportJob(claim, job));
    } catch (RuntimeException | Error e) {
      ValueSetsImportStatusManager.getInstance().finish(claim, e);
      log.error("Could not start the value sets ontology import; released the import claim", e);
      throw e;
    } finally {
      if (executor != null) {
        executor.shutdown();
      }
    }
  }

  private static void runValueSetsImportJob(JobClaim claim, IndexJobGuard.Job job) {
    ValueSetsImportStatusManager imports = ValueSetsImportStatusManager.getInstance();
    try {
      job.run();
      imports.finish(claim, null);
    } catch (Exception e) {
      imports.finish(claim, e);
      log.error("Error in load value sets ontology executor", e);
    } catch (Error e) {
      imports.finish(claim, e);
      log.error("Fatal error in load value sets ontology executor", e);
      throw e;
    }
  }

}
