package controllers;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.commons.lang3.StringUtils;
import org.metadatacenter.constant.HttpConstants;
import org.metadatacenter.model.CedarResource;
import org.metadatacenter.model.CedarResourceType;
import org.metadatacenter.model.request.ResourceListRequest;
import org.metadatacenter.model.response.ResourceListResponse;
import org.metadatacenter.provenance.ProvenanceTime;
import org.metadatacenter.provenance.ProvenanceUser;
import org.metadatacenter.server.IResourceService;
import org.metadatacenter.server.security.Authorization;
import org.metadatacenter.server.security.CedarAuthFromRequestFactory;
import org.metadatacenter.server.security.model.IAuthRequest;
import org.metadatacenter.server.security.model.auth.CedarPermission;
import org.metadatacenter.util.http.LinkHeaderUtil;
import org.metadatacenter.util.json.JsonUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import play.libs.F;
import play.mvc.Result;

import java.rmi.AccessException;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Collectors;

public class FolderController extends AbstractResourceServerController {
  private static Logger log = LoggerFactory.getLogger(FolderController.class);

  private static IResourceService resourceService;

  final static List<String> knownSortKeys;

  static {
    knownSortKeys = new ArrayList<>();
    knownSortKeys.add("name");
    knownSortKeys.add("createdOn");
    knownSortKeys.add("lastUpdatedOn");
  }

  public static void injectResourceService(IResourceService rs) {
    resourceService = rs;
  }

  public static Result createResource() {
    try {
      IAuthRequest frontendRequest = CedarAuthFromRequestFactory.fromRequest(request());
      Authorization.mustHavePermission(frontendRequest, CedarPermission.JUST_AUTHORIZED);

      CedarResource resource = null;

      CedarResource r = resourceService.createResource(resource);

      ObjectMapper mapper = new ObjectMapper();
      JsonNode createdUser = mapper.valueToTree(r);
      // Remove autogenerated _id field to avoid exposing it
      createdUser = JsonUtils.removeField(createdUser, "_id");
      // Set Location header pointing to the newly created template
      String absoluteUrl = "TODO";//routes.FolderController.findFolder(r.getResourceId()).absoluteURL(request());
      response().setHeader(HttpConstants.HTTP_HEADER_LOCATION, absoluteUrl);
      // Return created response
      return created(createdUser);
    } catch (IllegalArgumentException e) {
      return badRequestWithError(e);
    } catch (AccessException e) {
      return forbiddenWithError(e);
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }


  public static Result findFolder(F.Option<String> pathParam, F.Option<String> resourceTypes, F.Option<String> sort, F
      .Option<Integer> limitParam, F.Option<Integer> offsetParam) {
    try {

      // Test path
      String path;
      if (pathParam.isEmpty() || pathParam.get().length() == 0) {
        throw new IllegalArgumentException("You need to specify path as a request parameter!");
      }
      path = pathParam.get();
      if (path.endsWith("/") && path.length() > 1) {
        throw new IllegalArgumentException("Do not pass trailing / for paths!");
      }

      // Test resource types
      String resourceTypesString = null;
      if (resourceTypes.isEmpty() || resourceTypes.get().length() == 0) {
        throw new IllegalArgumentException("You need to specify resource_types as a request parameter!");
      } else {
        resourceTypesString = resourceTypes.get();
      }

      List<String> resourceTypeStringList = Arrays.asList(StringUtils.split(resourceTypesString, ","));
      List<CedarResourceType> resourceTypeList = new ArrayList<>();

      for (String t : resourceTypeStringList) {
        CedarResourceType rt = CedarResourceType.forValue(t);
        if (rt == null) {
          throw new IllegalArgumentException("You passed an illegal resource type:'" + t + "'. The allowed values " +
              "are:" + CedarResourceType.values());

        } else {
          resourceTypeList.add(rt);
        }
      }

      // Test limit
      int limit = 50; // set default
      if (limitParam.isDefined()) {
        if (limitParam.get() <= 0) {
          throw new IllegalArgumentException("You should specify a positive limit!");
        } else if (limitParam.get() > 100) {
          throw new IllegalArgumentException("You should specify a limit smaller than 100!");
        }
        limit = limitParam.get();
      }

      // Test offset
      int offset = 0;
      if (offsetParam.isDefined()) {
        if (offsetParam.get() < 0) {
          throw new IllegalArgumentException("You should specify a positive or zero offset!");
        }
        offset = offsetParam.get();
      }

      // Test sort
      String sortString;
      if (sort.isEmpty() || sort.get().length() == 0) {
        sortString = "name";
      } else {
        sortString = sort.get();
      }

      List<String> sortList = Arrays.asList(StringUtils.split(sortString, ","));
      for (String s : sortList) {
        String test = s;
        if (s != null && s.startsWith("-")) {
          test = s.substring(1);
        }
        if (!knownSortKeys.contains(test)) {
          throw new IllegalArgumentException("You passed an illegal sort type:'" + s + "'. The allowed values are:" +
              knownSortKeys);
        }
      }

      ResourceListResponse r = new ResourceListResponse();

      ResourceListRequest req = new ResourceListRequest();
      req.setLimit(limit);
      req.setOffset(offset);
      req.setPath(path);
      req.setResourceTypes(resourceTypeList);
      req.setSort(sortList);

      r.setRequest(req);


      ArrayList<CedarResource> resourceList = new ArrayList<>();

      generateRandomResources(resourceList, req, resourceTypeList);

      long total = offset + limit + ThreadLocalRandom.current().nextInt(10, 30);


      r.setTotalCount(total);
      r.setCurrentOffset(offset);

      r.setResources(resourceList);

      F.Option<Integer> none = new F.None<>();
      String absoluteUrl = routes.FolderController.findFolder(pathParam, resourceTypes, sort, none, none).absoluteURL
          (request());

      r.setPaging(LinkHeaderUtil.getPagingLinkHeaders(absoluteUrl, total, limit, offset));


      ObjectMapper mapper = new ObjectMapper();
      JsonNode resp = mapper.valueToTree(r);
      return ok(resp);

    } catch (IllegalArgumentException e) {
      return badRequestWithError(e);
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  private static void generateRandomResources(ArrayList<CedarResource> resourceList, ResourceListRequest req,
                                              List<CedarResourceType> resourceTypeList) {
    while (resourceList.size() < req.getLimit()) {
      int i = ThreadLocalRandom.current().nextInt(0, resourceTypeList.size());
      resourceList.add(generateOneResource(resourceTypeList.get(i), resourceList.size(),
          req));
    }
  }

  private static CedarResource generateOneResource(CedarResourceType type, int idx, ResourceListRequest req) {
    CedarResource newResource = CedarResource.forType(type);

    newResource.setId(UUID.randomUUID().toString());
    newResource.setName("Name " + idx);
    newResource.setDescription("Description " + idx);
    String path = req.getPath();
    if (!path.endsWith("/")) {
      path += "/";
    }
    path += newResource.getName();
    newResource.setPath(path);

    ProvenanceTime now = new ProvenanceTime(new Date());
    newResource.setCreatedOn(now);
    newResource.setLastUpdatedOn(now);

    ProvenanceUser u = new ProvenanceUser(UUID.randomUUID().toString(), "User Name " + idx);
    newResource.setCreatedBy(u);
    newResource.setLastUpdatedBy(u);

    return newResource;
  }


}
